### ISSUE TITLE
procurement 1.9.9 downloading stash tab error

### ISSUE THREAD

**Issue by zeella** [medvedttn/Procurement#11]
it seems that everytime when trying to downloading tab 18, it will hit the below error.
Loading Standard Stash Tab 13...                                                          [OK]
Loading Standard Stash Tab 14...                                                          [OK]
Loading Standard Stash Tab 16...                                                          [OK]
Loading Standard Stash Tab 18...                                                          [OK]

[Error] Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues

log file below;

[03-10-2015 12:17] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[03-10-2015 12:17] ItemFactory unable to instanciate type : Grotto Map
[03-10-2015 12:17] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Grotto Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league)
[03-10-2015 12:17] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()
[03-10-2015 12:30] System.NullReferenceException: Object reference not set to an instance of an object.
   at POEApi.Model.Map..ctor(Item item)
   at POEApi.Model.ItemFactory.Get(Item item)
[03-10-2015 12:30] ItemFactory unable to instanciate type : Grotto Map
[03-10-2015 12:30] Error downloading stash for Standard, exception details: System.Exception: ItemFactory unable to instanciate type : Grotto Map
   at POEApi.Model.ItemFactory.Get(Item item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at POEApi.Model.Stash..ctor(Stash proxy)
   at POEApi.Model.POEModel.GetStash(Int32 index, String league, Boolean forceRefresh)
   at POEApi.Model.POEModel.getAllTabs(String league, Stash stash)
   at POEApi.Model.POEModel.GetStash(String league)
[03-10-2015 12:30] System.Exception: Downloading stash for Standard, details logged to DebugInfo.log, please open a ticket at https://github.com/medvedttn/Procurement/issues
   at POEApi.Model.POEModel.GetStash(String league)
   at Procurement.ViewModel.LoginWindowViewModel.LoadStashItems(Character character)
   at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__6.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass2.<Login>b__1()
   at System.Threading.Tasks.Task.Execute()

**Comment by medvedttn** [comment]
Should be fixed in last 2.0.0 release (new "Map Tier" instead of "Map level" logic, also in template)
